name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:

jobs:
  check_validator:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Checks HTML5
          uses: Cyb3r-Jak3/html5validator-action@v7.1.1
          with:
            root: '.'
            # Can't recognize aspect-ratio rule
            css: false
